# Generated by Django 4.2.4 on 2023-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProbando', '0003_entregable_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='link',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
