# Generated by Django 4.2.4 on 2023-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProbando', '0004_entregable_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.ManyToManyField(to='AppProbando.curso'),
        ),
    ]
